import { carrier, battleship, destroyer, patrolBoat } from './ship.js';
import { gameBoard, placeShips } from './gameboard.js';

describe('test ships', () => {
    test('test if carrier can sink', () => {
        for (let i = 0; i < 3; i++) {
            carrier.hit();
        }
        expect(carrier.hit()).toMatch(/Carrier is sunk/);
    });

    test('test if battleship can sink', () => {
        for (let i = 0; i < 2; i++) {
            battleship.hit();
        }
        expect(battleship.hit()).toMatch(/Battleship is sunk/);
    });

    test('test if destroyer can sink', () => {
        destroyer.hit();
        expect(destroyer.hit()).toMatch(/Destroyer is sunk/);
    });

    test('test if destroyer can sink', () => {
        expect(patrolBoat.hit()).toMatch(/Patrol Boat is sunk/);
    });
});

describe('test gameBoard', () => {
    test('check if the ship get placed', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(6, 1, 9, board, ships, 1)).toBeTruthy();
    });

    test('check if the ship get placed 2', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(6, 10, 9, board, ships, 1)).toBeTruthy();
    });

    test('check if the ship get placed 3', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(6, 4, 4, board, ships, 1)).toBeFalsy();
    });

    test('check if the ship get placed 4', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(3, 1, 9, board, ships, 1)).toBeFalsy();
    });

    test('check if the ship get placed 5', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(3, 0, 0, board, ships, 1)).toBeFalsy();
    });

    test('check if the ship get placed 6', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(6, 0, 0, board, ships, 1)).toBeFalsy();
    });

    test('check if the ship get placed 7', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(3, 9, 9, board, ships, 1)).toBeTruthy();
    });

    test('check if the ship get placed 8', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(6, 9, 9, board, ships, 1)).toBeTruthy();
    });

    test('check if the ship get placed 9.1', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(3, 0, 9, board, ships, 1)).toBeFalsy();
    });

    test('check if the ship get placed 9.2', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(7, 0, 9, board, ships, 1)).toBeTruthy();
    });

    test('check if the ship get placed 10.1', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(3, 0, 0, board, ships, 1)).toBeFalsy();
    });

    test('check if the ship get placed 10.2', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(7, 0, 0, board, ships, 1)).toBeFalsy();
    });

    test('check if the ship get placed 11.1', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(7, 9, 0, board, ships, 1)).toBeFalsy();
    });

    test('check if the ship get placed 11.2', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(3, 9, 0, board, ships, 1)).toBeTruthy();
    });

    test('check if the ship get placed 12.1', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(3, 9, 9, board, ships, 1)).toBeTruthy();
    });

    test('check if the ship get placed 12.2', () => {
        let board = [
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
            [
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
                { ship: null },
            ],
        ];
        let ships = [carrier, battleship, destroyer, patrolBoat];
        expect(placeShips(7, 9, 9, board, ships, 1)).toBeTruthy();
    });

    // test('check if the carrier can get hit', () => {
    //     expect(gameBoard.receiveAttack('a5')).toMatch(/Carrier got hit/);
    // });
    // test('check when the hit misses', () => {
    //     expect.(gameBoard.receiveAttack('h1')).toMatch(/missed/);
    // })
});
